// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadLocalKlines(arg1) {
  return window['go']['main']['App']['LoadLocalKlines'](arg1);
}

export function RunBacktest(arg1) {
  return window['go']['main']['App']['RunBacktest'](arg1);
}

export function RunBoxRangeBacktest(arg1) {
  return window['go']['main']['App']['RunBoxRangeBacktest'](arg1);
}

export function RunEMABacktest(arg1) {
  return window['go']['main']['App']['RunEMABacktest'](arg1);
}
