// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {market} from '../models';
import {backtest} from '../models';

export function LoadLocalKlines(arg1:string):Promise<Array<market.KLine>>;

export function RunBacktest(arg1:backtest.RunRequest):Promise<backtest.Report>;

export function RunBoxRangeBacktest(arg1:backtest.RunBoxRangeRequest):Promise<backtest.BoxRangeReport>;

export function RunEMABacktest(arg1:backtest.RunEMARequest):Promise<backtest.EMAReport>;
